### ISSUE TITLE
Javascript Errors

### ISSUE THREAD

**Issue by JayVerb** [edalzell/statamic-mailchimp#11]
Just went into the settings page and noticed I couldn't trigger any of the toggle buttons. In the console, I see this error...

`Unhandled Promise Rejection: TypeError: self.loadFields is not a function. (In 'self.loadFields()', 'self.loadFields' is undefined)`

Tested in both latest Chrome and Safari on Mac 10.12.6.

Great Plugin, but will it allow for a checkbox opt in/out on the signup form? Keep up with the great addons!

**Comment by edalzell** [comment]
I’ll look into this today. Thanks for the report.

**Comment by edalzell** [comment]
@JayVerb what version of Mailchimp do you have?

On my version I can toggle everything. And yes, it will allow an opt-in checkbox.

**Comment by JayVerb** [comment]
I have version 1.3

**Comment by JayVerb** [comment]
2.8.10

**Comment by raullukacs** [comment]
I have the same issue in 2.8.11 as well.

Uncaught (in promise) TypeError: self.loadFields is not a function
    at GridFieldtype.$parent.$watch.deep (fieldtype.js:64)
    at re.run (johnny-deps.js?v=2.8.11:7)
    at ne (johnny-deps.js?v=2.8.11:6)
    at Array.ee (johnny-deps.js?v=2.8.11:6)
    at t (johnny-deps.js?v=2.8.11:7)

**Comment by edalzell** [comment]
@JayVerb @raullukacs what browsers and OS?

**Comment by raullukacs** [comment]
@edalzell 

Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Windows 10.

**Comment by edalzell** [comment]
I think this is fixed in the latest release (1.3.3).
