### ISSUE TITLE
updates fail because of dependencies

### ISSUE THREAD

**Issue by PeterEmil** [edalzell/statamic-mailchimp#13]
MailChimp is the only add-on added to Statamic. Every update fails because of an error relating to dependencies. My best guess is it has something to do with this add-on.
Latest update to Statamic v2.8.11 renders this error:
"Couldn't install dependencies.
The process has been signaled with signal "9"." When I temporarily delete the add-on upgrade goes fine.

**Comment by edalzell** [comment]
If you update from the command line, do you get more detailed errors?

**Comment by PeterEmil** [comment]
It's only on the server and unfortunately I can't get there using command line. So then I'll have to update Statamic via the CP. This throws that error. Only way to circumvent this is to remove the add-on, update Statamic, and put the add-on back.

Local everything just runs fine.

**Comment by edalzell** [comment]
You shouldn't be updating on the server, you should be updating on local and pushing everything to the server.

Without additional errors, this is extremely difficult to troubleshoot. It's likely the server is missing some packages that are required. I had the same issue on Dreamhost.

Going to close this, unfortunately, if you can get some more details please re-open and I'll look at it.
