### ISSUE TITLE
Check Permission is working backwords

### ISSUE THREAD

**Issue by raullukacs** [edalzell/statamic-mailchimp#17]
Hi,

It seems the check permissions is working reverse of what it should do.

If I check "no" the email to check permissions is sent. (& the user is added in the mailchimp list only if I confirm from the email)

If I check "yes" the email is not sent and the user is not added in the mailchimp list.

Can you please help with this?

Thanks,

**Comment by edalzell** [comment]
I'm not sure this is a bug @raullukacs, as Mailchimp does the opt-in if you haven't sent a check_permission field.

Can you please show me your `mailchimp.yaml` file?

**Comment by raullukacs** [comment]
Do you know where I can find the mailchimp.yaml file ?

I can confirm that double-opt in is not checked on the list.

Thanks,

**Comment by edalzell** [comment]
It in `site/settings/addons`

**Comment by raullukacs** [comment]
Here you go: ( I removed the keys)

mailchimp_key: XXXXXXXXXXXXXXXXXXXXXXXXX
add_new_users: false
forms:
  - 
    mailchimp_list_id: XXXXXXX
    form: become-ambassador
  - 
    mailchimp_list_id: XXXXXXX
    form: newsletter
license_key: ""

**Comment by edalzell** [comment]
Right so under those settings, I would expect Mailchimp to send the opt-in email as you are not intentionally bypassing it (and you shouldn't) and you are not sending check permissions data.

**Comment by raullukacs** [comment]
@edalzell And if I want to bypass it, is there a setting like check_permission: false I can put in the yaml file or somewhere else?

Thanks,

**Comment by edalzell** [comment]
Like it says in the docs `Not recommended, but you can disable the Double Opt In`.

**Comment by raullukacs** [comment]
@edalzell Ok . Thanks for all your help.
