### ISSUE TITLE
Does the add-on give any feedback

### ISSUE THREAD

**Issue by KimKJDesigns** [edalzell/statamic-mailchimp#23]
I'm having a few subscribers, who have unsubscribed in the past, now subscribing to our list again. 

Logs are giving me some feedback but some information I'd like to pass onto the user. Is this an option through the add-on? 

Currently, we just pass a simple message based on the form:success or form:errors.

**Comment by edalzell** [comment]
What kind of message are you looking for?

**Comment by edalzell** [comment]
Closed due to inactivity. Please re-open if still relevant.
