### ISSUE TITLE
Error message on install

### ISSUE THREAD

**Issue by zeddyblue** [edalzell/statamic-mailchimp#24]
I get the following error on install. Is this something to worry about as it does say Dependencies updated! 

Adding packages: erin-dalzell/mailchimp
Please wait while dependencies are updated via Composer. This may take a while.
The command "php composer.phar update erin-dalzell/mailchimp --prefer-dist --no-dev --optimize-autoloader" failed.
Exit Code: 137(Kill (terminate immediately))

Output:
================

Error Output:
================
Loading composer repositories with package information
Updating dependencies
Killed

Dependencies updated!

**Comment by edalzell** [comment]
What's the error?

**Comment by zeddyblue** [comment]
The command "php composer.phar update erin-dalzell/mailchimp --prefer-dist --no-dev --optimize-autoloader" failed.
Exit Code: 137(Kill (terminate immediately))

**Comment by edalzell** [comment]
Ya that's not to do with me. Are you trying that on production, or is this locally?

**Comment by zeddyblue** [comment]
Thanks. It was some issue on the production server. Was in the process of moving servers and works fine on the new forge server, so i don't know what the problem was on the old server.
